# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    version = "3.3.1"
    hostname = "iojs.box"
    locale = "en_GB.UTF.8"
    path = "iojs-v#{version}-linux-x64"

    # Box
    config.vm.box = "ubuntu/trusty64"

    # Forward port
    config.vm.network "forwarded_port", guest: 9991, host: 9991, host_ip: "127.0.0.1"

    # Shared folders
    config.vm.synced_folder ".", "/srv"

    # Setup
    config.vm.provision :shell, :inline => "touch .hushlogin"
    config.vm.provision :shell, :inline => "hostnamectl set-hostname #{hostname} && locale-gen #{locale}"
    config.vm.provision :shell, :inline => "apt-get update --fix-missing"
    config.vm.provision :shell, :inline => "apt-get install -q -y g++ make git curl vim-gnome build-essential cmake python-dev"
    config.vm.provision :shell, :inline => "curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    config.vm.provision :shell, :inline => "wget https://raw.githubusercontent.com/lw7360/vimrc/master/.vimrc"

    # Lang
    config.vm.provision :shell, :inline => "echo 'fetching #{path}' && wget -q https://iojs.org/dist/v#{version}/#{path}.tar.xz"
    config.vm.provision :shell, :inline => "tar -C /usr/local -xpvf #{path}.tar.xz"
    config.vm.provision :shell, :inline => "echo 'export PATH=$PATH:/usr/local/#{path}/bin' > .bash_profile"

end
